# Generated by Django 2.1.5 on 2019-01-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfosAbstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='书名')),
                ('img_url', models.CharField(max_length=50, null=True, verbose_name='封面图片')),
                ('file_path', models.CharField(max_length=100, verbose_name='文件地址')),
                ('create_time', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
