# Generated by Django 2.1.5 on 2019-01-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarkBook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinfosabstract',
            options={'verbose_name': '文档信息表'},
        ),
        migrations.AlterModelTable(
            name='bookinfosabstract',
            table='book_info',
        ),
    ]
